In [1]:
import os
import zipfile as zip

import pandas as pd

In [2]:
folder = 'data/censo-educacao-superior/'

files = os.listdir(folder)
df = pd.DataFrame()

for file in files:
    with zip.ZipFile(folder + file, 'r') as zip_file:
        for name in zip_file.namelist():
            if name.find('MICRODADOS_CADASTRO_CURSOS_2020') > 0:
                with zip_file.open(name) as csv_file:
                    df_tmp = pd.read_csv(csv_file, encoding='latin1', sep=';')
                    df = df.append(df_tmp)
            else:
                pass

/tmp/ipykernel_4276/1368418920.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(df_tmp)

In [3]:
df.head()

,NU_ANO_CENSO,NO_REGIAO,CO_REGIAO,NO_UF,SG_UF,CO_UF,NO_MUNICIPIO,CO_MUNICIPIO,IN_CAPITAL,TP_ORGANIZACAO_ACADEMICA,...,QT_MAT_APOIO_SOCIAL,QT_CONC_APOIO_SOCIAL,QT_ATIV_EXTRACURRICULAR,QT_ING_ATIV_EXTRACURRICULAR,QT_MAT_ATIV_EXTRACURRICULAR,QT_CONC_ATIV_EXTRACURRICULAR,QT_MOB_ACADEMICA,QT_ING_MOB_ACADEMICA,QT_MAT_MOB_ACADEMICA,QT_CONC_MOB_ACADEMICA
0,2020,Centro-Oeste,5.0,Mato Grosso,MT,51.0,Água Boa,5100201.0,0.0,1,...,0,0,0,0,0,0,0,0,0,0
1,2020,Centro-Oeste,5.0,Mato Grosso,MT,51.0,Água Boa,5100201.0,0.0,1,...,0,0,0,0,0,0,0,0,0,0
2,2020,Centro-Oeste,5.0,Mato Grosso,MT,51.0,Água Boa,5100201.0,0.0,1,...,0,0,0,0,0,0,0,0,0,0
3,2020,Centro-Oeste,5.0,Mato Grosso,MT,51.0,Alto Araguaia,5100300.0,0.0,1,...,0,0,0,0,0,0,0,0,0,0
4,2020,Centro-Oeste,5.0,Mato Grosso,MT,51.0,Arenápolis,5101308.0,0.0,1,...,0,0,0,0,0,0,0,0,0,0

In [4]:
df.tail()

,NU_ANO_CENSO,NO_REGIAO,CO_REGIAO,NO_UF,SG_UF,CO_UF,NO_MUNICIPIO,CO_MUNICIPIO,IN_CAPITAL,TP_ORGANIZACAO_ACADEMICA,...,QT_MAT_APOIO_SOCIAL,QT_CONC_APOIO_SOCIAL,QT_ATIV_EXTRACURRICULAR,QT_ING_ATIV_EXTRACURRICULAR,QT_MAT_ATIV_EXTRACURRICULAR,QT_CONC_ATIV_EXTRACURRICULAR,QT_MOB_ACADEMICA,QT_ING_MOB_ACADEMICA,QT_MAT_MOB_ACADEMICA,QT_CONC_MOB_ACADEMICA
335624,2020,Centro-Oeste,5.0,Mato Grosso,MT,51.0,Rondonópolis,5107602.0,0.0,1,...,12,1,41,3,40,4,0,0,0,0
335625,2020,Centro-Oeste,5.0,Mato Grosso,MT,51.0,Rondonópolis,5107602.0,0.0,1,...,48,8,21,0,21,2,0,0,0,0
335626,2020,Centro-Oeste,5.0,Mato Grosso,MT,51.0,Rondonópolis,5107602.0,0.0,1,...,23,2,77,0,74,6,0,0,0,0
335627,2020,Centro-Oeste,5.0,Mato Grosso,MT,51.0,Rondonópolis,5107602.0,0.0,1,...,8,1,42,1,40,0,0,0,0,0
335628,2020,Centro-Oeste,5.0,Mato Grosso,MT,51.0,Rondonópolis,5107602.0,0.0,1,...,19,11,79,5,77,10,0,0,0,0

In [5]:
df.shape

(335629, 196)

In [6]:
df['QT_VG_TOTAL'].describe()

count    335629.000000
mean         58.484434
std        1126.038638
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max      149108.000000
Name: QT_VG_TOTAL, dtype: float64

In [7]:
tabela = df['NO_MUNICIPIO'].drop_duplicates()
tabela

0                Água Boa
3           Alto Araguaia
4              Arenápolis
5                Aripuanã
8         Barra do Garças
               ...
334463        Piratininga
334832         Alto Santo
335069         Bertópolis
335103     Afonso Bezerra
335111      Vista Serrana
Name: NO_MUNICIPIO, Length: 2713, dtype: object

In [8]:
df.columns

Index(['NU_ANO_CENSO', 'NO_REGIAO', 'CO_REGIAO', 'NO_UF', 'SG_UF', 'CO_UF',
       'NO_MUNICIPIO', 'CO_MUNICIPIO', 'IN_CAPITAL',
       'TP_ORGANIZACAO_ACADEMICA',
       ...
       'QT_MAT_APOIO_SOCIAL', 'QT_CONC_APOIO_SOCIAL',
       'QT_ATIV_EXTRACURRICULAR', 'QT_ING_ATIV_EXTRACURRICULAR',
       'QT_MAT_ATIV_EXTRACURRICULAR', 'QT_CONC_ATIV_EXTRACURRICULAR',
       'QT_MOB_ACADEMICA', 'QT_ING_MOB_ACADEMICA', 'QT_MAT_MOB_ACADEMICA',
       'QT_CONC_MOB_ACADEMICA'],
      dtype='object', length=196)

In [9]:
columns = ['NU_ANO_CENSO','CO_IES','CO_MUNICIPIO','CO_CINE_ROTULO','NO_CINE_ROTULO','TP_GRAU_ACADEMICO','TP_MODALIDADE_ENSINO','TP_NIVEL_ACADEMICO',
           'QT_VG_TOTAL','QT_INSCRITO_TOTAL','QT_ING','QT_MAT','QT_CONC']

ft_oferta_curso = df[columns]

In [10]:
name_columns = {'NU_ANO_CENSO': 'NR_ANO',
                'CO_IES': 'CD_IES',
                'CO_MUNICIPIO': 'CD_MUNICIPIO',
                'CO_CINE_ROTULO': 'CD_CURSO',
                'NO_CINE_ROTULO': 'NM_CURSO',
                'TP_GRAU_ACADEMICO': 'CD_GRAU_ACADEMICO',
                'TP_MODALIDADE_ENSINO': 'CD_MODALIDADE_ENSINO',
                'TP_NIVEL_ACADEMICO': 'CD_NIVEL_ACADEMICO',
                'QT_VG_TOTAL': 'QT_OFERTA_TOTAL',
                'QT_INSCRITO_TOTAL': 'QT_INSCRITO_TOTAL',
                'QT_ING': 'QT_INGRESSANTE_TOTAL',
                'QT_MAT': 'QT_MATRICULA_TOTAL',
                'QT_CONC': 'QT_CONCLUINTE_TOTAL'}

ft_oferta_curso.rename(columns=name_columns, inplace=True)
ft_oferta_curso

/tmp/ipykernel_4276/417977560.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ft_oferta_curso.rename(columns=name_columns, inplace=True)

,NR_ANO,CD_IES,CD_MUNICIPIO,CD_CURSO,NM_CURSO,CD_GRAU_ACADEMICO,CD_MODALIDADE_ENSINO,CD_NIVEL_ACADEMICO,QT_OFERTA_TOTAL,QT_INSCRITO_TOTAL,QT_INGRESSANTE_TOTAL,QT_MATRICULA_TOTAL,QT_CONCLUINTE_TOTAL
0,2020,1,5100201.0,0113P01,Pedagogia,2.0,2,1,0,0,0,38,0
1,2020,1,5100201.0,0114C05,Computação formação de professor,2.0,2,1,0,0,14,28,0
2,2020,1,5100201.0,0413A02,Administração pública,1.0,2,1,0,0,0,34,0
3,2020,1,5100300.0,0114M01,Matemática formação de professor,2.0,2,1,0,0,0,22,0
4,2020,1,5101308.0,0113P01,Pedagogia,2.0,2,1,0,0,33,33,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
335624,2020,25352,5107602.0,"7,15E+04",Engenharia mecânica,1.0,1,1,86,43,40,378,17
335625,2020,25352,5107602.0,"8,11E+03",Engenharia agrícola,1.0,1,1,96,64,63,341,18
335626,2020,25352,5107602.0,0811Z01,Zootecnia,1.0,1,1,68,55,55,279,10
335627,2020,25352,5107602.0,0912M01,Medicina,1.0,1,1,45,62,46,205,6
335628,2020,25352,5107602.0,"9,13E+03",Enfermagem,1.0,1,1,30,22,21,127,18

In [11]:
df_maringa = ft_oferta_curso.query('CD_MUNICIPIO == 4115200 & CD_IES == 1196 & CD_MODALIDADE_ENSINO == 1')
df_maringa

,NR_ANO,CD_IES,CD_MUNICIPIO,CD_CURSO,NM_CURSO,CD_GRAU_ACADEMICO,CD_MODALIDADE_ENSINO,CD_NIVEL_ACADEMICO,QT_OFERTA_TOTAL,QT_INSCRITO_TOTAL,QT_INGRESSANTE_TOTAL,QT_MATRICULA_TOTAL,QT_CONCLUINTE_TOTAL
185427,2020,1196,4115200.0,0113P01,Pedagogia,2.0,1,1,107,148,52,190,29
185429,2020,1196,4115200.0,0114A02,Artes visuais formação de professor,2.0,1,1,0,0,0,4,4
185431,2020,1196,4115200.0,0114B01,Biologia formação de professor,2.0,1,1,114,52,29,44,9
185434,2020,1196,4115200.0,"1,14E+05",Educação física formação de professor,2.0,1,1,221,207,92,171,23
185440,2020,1196,4115200.0,0114M02,Música formação de professor,2.0,1,1,0,0,0,6,6
185442,2020,1196,4115200.0,0212D03,Design de interiores,3.0,1,1,0,0,0,1,1
185445,2020,1196,4115200.0,0212M01,Moda,1.0,1,1,4,2,1,49,19
185446,2020,1196,4115200.0,0212M01,Moda,3.0,1,1,77,88,57,37,0
185450,2020,1196,4115200.0,0313P01,Psicologia,1.0,1,1,260,717,190,615,108
185451,2020,1196,4115200.0,0321C01,Comunicação social,1.0,1,1,127,115,53,42,0
185452,2020,1196,4115200.0,0321J01,Jornalismo,1.0,1,1,0,0,0,12,12
185453,2020,1196,4115200.0,0411C01,Contabilidade,1.0,1,1,127,232,59,158,34
185456,2020,1196,4115200.0,0413A01,Administração,1.0,1,1,231,397,116,219,38
185458,2020,1196,4115200.0,0413C01,Comércio exterior,3.0,1,1,0,0,0,6,6
185462,2020,1196,4115200.0,0413G05,Gestão de negócios,3.0,1,1,212,48,25,43,22
185464,2020,1196,4115200.0,0413G07,Gestão de pessoas,3.0,1,1,0,0,0,1,0
185470,2020,1196,4115200.0,0414P01,Publicidade e propaganda,1.0,1,1,136,187,49,136,28
185474,2020,1196,4115200.0,0421D01,Direito,1.0,1,1,569,1106,313,1275,265
185475,2020,1196,4115200.0,0511B01,Biologia,1.0,1,1,69,58,13,44,19
185477,2020,1196,4115200.0,"6,13E+03",Engenharia de software,1.0,1,1,123,229,106,220,29
185479,2020,1196,4115200.0,0615S02,Sistemas de informação,3.0,1,1,141,191,63,81,7
185481,2020,1196,4115200.0,0615S03,Sistemas para internet,3.0,1,1,0,0,0,0,0
185483,2020,1196,4115200.0,"7,11E+07",Engenharia química,1.0,1,1,0,0,0,27,21
185484,2020,1196,4115200.0,"7,12E+04",Engenharia ambiental e sanitária,1.0,1,1,0,0,0,12,12
185486,2020,1196,4115200.0,"7,13E+07",Engenharia elétrica,1.0,1,1,68,60,1,35,15
185488,2020,1196,4115200.0,0714A01,Automação industrial,3.0,1,1,0,0,0,1,0
185489,2020,1196,4115200.0,"7,14E+07",Engenharia de controle e automação,1.0,1,1,106,74,34,91,12
185491,2020,1196,4115200.0,"7,15E+04",Engenharia mecânica,1.0,1,1,108,159,36,158,46
185493,2020,1196,4115200.0,0716M01,Manutenção de aeronaves,3.0,1,1,0,0,0,0,0
185496,2020,1196,4115200.0,"7,25E+04",Engenharia de produção,1.0,1,1,118,16,0,39,14
185498,2020,1196,4115200.0,0731A02,Arquitetura e urbanismo,1.0,1,1,181,262,76,362,89
185499,2020,1196,4115200.0,"7,32E+03",Engenharia civil,1.0,1,1,249,228,60,309,80
185502,2020,1196,4115200.0,0811A04,Agronomia,1.0,1,1,225,273,78,301,73
185503,2020,1196,4115200.0,0841M01,Medicina veterinária,1.0,1,1,130,410,82,320,51
185504,2020,1196,4115200.0,0911O01,Odontologia,1.0,1,1,295,451,118,424,97
185505,2020,1196,4115200.0,0912M01,Medicina,1.0,1,1,558,3452,368,1625,152
185506,2020,1196,4115200.0,"9,13E+03",Enfermagem,1.0,1,1,247,549,152,334,60
185507,2020,1196,4115200.0,0914B01,Biomedicina,1.0,1,1,229,366,85,234,43
185508,2020,1196,4115200.0,"9,15E+03",Educação física,1.0,1,1,343,231,107,229,113
185510,2020,1196,4115200.0,0915F01,Fisioterapia,1.0,1,1,302,407,130,413,89
185511,2020,1196,4115200.0,0915F02,Fonoaudiologia,1.0,1,1,111,74,41,85,16
185512,2020,1196,4115200.0,0915N01,Nutrição,1.0,1,1,288,188,57,227,92
185514,2020,1196,4115200.0,0916F01,Farmácia,1.0,1,1,124,154,63,127,21
185517,2020,1196,4115200.0,"1,01E+04",Estética e cosmética,3.0,1,1,198,224,64,192,61
185519,2020,1196,4115200.0,1013G01,Gastronomia,3.0,1,1,220,173,53,97,36
185523,2020,1196,4115200.0,1041C01,Ciências aeronáuticas,3.0,1,1,59,66,21,46,23

In [12]:
df_maringa['QT_OFERTA_TOTAL'].describe()

count     46.000000
mean     145.152174
std      134.692566
min        0.000000
25%       17.750000
50%      123.500000
75%      224.000000
max      569.000000
Name: QT_OFERTA_TOTAL, dtype: float64

In [13]:
df_cesumar = df_maringa[:15]
df_cesumar.plot.bar(x='NM_CURSO', y='QT_MATRICULA_TOTAL')

ImportError: matplotlib is required for plotting when the default backend "matplotlib" is selected.